[package]
name = "i18n-editor"
version = "0.1.0"
edition = "2021"

[lib]
name = "i18n_editor_lib"
crate-type = ["lib", "cdylib", "staticlib"]
path = "src/lib.rs"

[[bin]]
name = "i18n-editor"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
tauri = { version = "2", features = [] }
rfd = "0.15"

[dev-dependencies]
tempfile = "3"
